[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pyqt6>=6.9.0",
    "pyqt6-webengine>=6.9.0",
    "pysocks>=1.7.1",
    "requests>=2.32.3",
    "socks>=0",
]
